apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-lookup
  description: Artist Lookup
  labels:
    accelerate:
      jiraboard: CG
      statuspageComponent: FAST
spec:
  type: service
  lifecycle: experimental
  owner: artists@example.com
